defaults:
  - text2semantic_pretrain_small
  - _self_

project: text2semantic_pretrain_large_cora_r16
max_length: 2048 
ckpt_path: checkpoints/consolidated.00.pth
resume_weights_only: true

trainer:
  accumulate_grad_batches: 2
  strategy: ddp_find_unused_parameters_true

data:
  _target_: fish_speech.datasets.text.TextDataModule
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}
  num_workers: 6
  batch_size: 8 
  tokenizer: ${tokenizer}
  max_length: ${max_length}

train_dataset:
  _target_: fish_speech.datasets.text.AutoAugTextDataset
  phones_prob: 0.
  interactive_prob: 0.
  use_delay_pattern: false 

val_dataset:
  _target_: fish_speech.datasets.text.AutoAugTextDataset
  phones_prob: 0.
  interactive_prob: 0.
  use_delay_pattern: false
  
# Model Configuration
model:
  model:
    config:
      max_seq_len: 4048
      n_layer: 32
      n_head: 32
      dim: 4096

  save_lora_only: false
  lora_config:
    _target_: fish_speech.models.text2semantic.lit_module.LoraConfig
    r: 16
    lora_alpha: 32

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.LambdaLR
    _partial_: true
    lr_lambda:
      _target_: fish_speech.scheduler.get_cosine_schedule_with_warmup_lr_lambda
      _partial_: true
      num_warmup_steps: 2000
      num_training_steps: ${trainer.max_steps}
      final_lr_ratio: 0.1

  optimizer:
    weight_decay: 1e-4
