_target_: fish_speech.models.text2semantic.llama.DualARTransformer
config:
  _target_: fish_speech.models.text2semantic.llama.DualARModelArgs
  max_seq_len: 4048
  vocab_size: 36408
  n_layer: 32
  n_fast_layer: 4
  n_head: 32
  dim: 4096
  rope_base: 10000
  norm_eps: 1e-5
  num_codebooks: 2  # input/output codebook size
  codebook_size: 1032 # codebook size 256 + 2 special tokens

